### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_EndGame_SugarLake.SugarLake#1]
- [x] Upload KI testen
- [x] Triggergrößen überdenken
- [x] Taskbeschreibungen anpassen
- [x] Kreise fixen
- [x] Uploadobjekte überprüfen
- [x] BRDM Ersatzräder?
- [x] Vorbereitungszeit zurück auf 5min
- [x] Upload Speed überdenken
